name: Tests

on:
  push:
    branches:
      - main
      - 'feature/*'
    paths:
      - '**.php'
      - 'composer.json'
      - 'composer.lock'
      - 'phpunit.xml.dist'
      - 'pint.json'
      - '.github/workflows/run-tests.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**.php'
      - 'composer.json'
      - 'composer.lock'
      - 'phpunit.xml.dist'
      - 'pint.json'
      - '.github/workflows/run-tests.yml'
  workflow_dispatch:

jobs:
  pint:
    name: Code Style (Pint)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring
          coverage: none

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress

      - name: Execute Code Style Check
        run: vendor/bin/pint --test

  test:
    name: Filament ${{ matrix.filament }} - PHP ${{ matrix.php }}
    needs: [pint]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.2', '8.4']
        filament: ['^4.0', '^5.0']
        dependency-version: [prefer-stable]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, intl, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "filament/filament:${{ matrix.filament }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/pest
